blogger_blog:
    resource: "@BloggerBlogBundle/Controller/"
    type:     annotation
    prefix:   /

#disable default routing
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
