# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    bloggerblog.comments.latest_comment_limit: 7

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    blog.repository:
        class: Blogger\BlogBundle\Repository\BlogRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - Blogger\BlogBundle\DomainObject\Blog
    comment.repository:
        class: Blogger\BlogBundle\Repository\CommentRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Blogger\BlogBundle\DomainObject\Comment

# services/handlers

    blog.service:
        class: Blogger\BlogBundle\Services\BlogService
        arguments: ["@blog.repository"]
    comment.service:
        class: Blogger\BlogBundle\Services\CommentService
        arguments: ['@comment.repository']

# twig extension
    blogger.twig.extension:
        class: Blogger\BlogBundle\Twig\Extension\BloggerBlogExtension
        tags:
            - { name : twig.extension }