# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    blog.repository:
        class: Blogger\BlogBundle\Repository\BlogRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - Blogger\BlogBundle\DomainObject\Blog

    blog.service:
        class: Blogger\BlogBundle\Services\BlogServices
        arguments: ["@blog.repository"]